### PR TITLE
feature: the possibility of EMV terminal using was added

### PR DESCRIPTION
**Pull request by Yankee-by**

### CODE REVIEW

**Comment by dearwish** [comment]
Hi @Yankee-by,
Not sure I understand how these changes are adding the EMV support.
Did you test it?

**Comment by Yankee-by** [comment]
Hi. For an EMV using we should make possible to change "version" request parameter. The value of version of old terminal type is "1001". The request to EMV terminal should contain "version" = "2000".

Yes, I have tested it.

**Comment by dearwish** [comment]
Great, thanks. I am approving it.

**Comment by mderazon** [comment]
Thank you,
And also thanks for typo fixes

**Pull request merged**
